all:
	coqc -I ../utils refocusing_lang_cs
	coqc -I ../utils refocusing_signatures_cs
	coqc -I ../utils refocusing_substitutions_cs
	coqc -I ../utils call_by_value_callcc_sub
	coqc -I ../utils call_by_name_callcc_sub
