all:
	coqc -I ../utils refocusing_lang
	coqc -I ../utils refocusing_signatures
	coqc -I ../utils refocusing_substitutions
	coqc -I ../utils simple_arith
	coqc -I ../utils call_by_value_sub
	coqc -I ../utils call_by_name_sub
	coqc -I ../utils miniml