all:
	coqc -I ../utils refocusing_lang_env
	coqc -I ../utils refocusing_signatures_env
	coqc -I ../utils refocusing_environments
	coqc -I ../utils call_by_name_environments
	coqc -I ../utils call_by_value_environments
