all:
	coqc -I ../utils refocusing_lang_env_cs
	coqc -I ../utils refocusing_signatures_env_cs
	coqc -I ../utils refocusing_environments_cs
#	coqc -I ../utils call_by_name_environments
#	coqc -I ../utils call_by_value_environments
